---
- name: "Cleanup certain files in {{ contra_env_setup_dir }}, kube config, and minishift profile"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ contra_env_setup_dir }}/.yml"
    - "{{ contra_env_setup_dir }}/.yaml"
  ignore_errors: yes

# Determine if project directory exists
- name: "Is project repository present in {{ project_dir }}"
  stat:
    path: "{{ project_dir }}"
  register: pd_is_found

# Remove project directory
- name: "Cleanup {{ project_dir }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ contra_env_setup_dir }}/{{ project_dir }}"
  when:
    - pd_is_found.stat.exists
    - force_repo_clone|bool == true
