---
- name: "Checking if helm binary is present in {{ minishift_dest_dir }}"
  stat:
    path: "{{ minishift_dest_dir }}/helm"
  register: helm_bin

- name: "Pull down and extract helm binary to {{ ansible_env.HOME }}"
  unarchive:
    src: "{{ helm_url }}"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes
  when: helm_bin.stat.exists == false

- name: "Copy helm binary to {{ ansible_env.HOME }}/minishift/"
  command: cp {{ ansible_env.HOME }}/linux-amd64/helm {{ minishift_dest_dir }}/
  when: helm_bin.stat.exists == false

- name: "Delete {{ ansible_env.HOME }}/linux-amd64"
  file:
    path: "{{ ansible_env.HOME }}/linux-amd64"
    state: absent
  when: helm_bin.stat.exists == false
