---
# tasks file for Jenkins pipelines

# Check if Jenkins is running
- name: "Check to see if a Jenkins Master instance is running"
  shell: "{{ oc_bin }} get pods | grep -i 'running' | grep -i 'jenkins' | tail -1 |  awk '{print $1}'"
  register: jenkins_running
  ignore_errors: yes

# Setup project and sample pipeline setup_pipelines.yml
- name: "Setup project_repo and sample pipelines"
  import_tasks: setup_pipelines.yml
  when: jenkins_running.stdout != ""