---
# tasks file for pipeline

# get ip of the cluster
- name: "Get the cluster Server URL for project {{ project }}"
  shell: oc status  | egrep '{{ project }}.*server' | awk '{print $NF}'
  register: cluster_ip

# set the oc client for the profile in use
- name: "Set the oc client for the profile in use"
  include: set_oc_client.yml

# login to the cluster for the profile in use
- include: login_to_cluster.yml

# create project
- name: "Create project {{ project }}"
  include: get_set_project.yml

# clone the pipeline repo
- name: "Clone the pipeline repo {{ pipeline_repo }}"
  include: clone_pipeline.yml
  when: force_repo_clone|bool == true

# NEED CHANGE HERE!
# The idea is create a parameter/argument to call ansible playbook on the repo cloned