---
- name: "Check if the minishift profile exists and are running"
  shell: "{{ minishift_dest_dir }}/minishift status --profile {{ profile }} | head -1 | awk '{print $2}'"
  register: minishift_exist
  ignore_errors: yes
  when: skip_clean == false

- name: "Stop the minishift if is already up and running"
  command: "{{ minishift_dest_dir }}/minishift stop --profile {{ profile }}"
  when: minishift_exist.stdout == "Running"

- name: "Remove minishift profile"
  command: "{{ minishift_dest_dir }}/minishift delete --profile {{ profile }} --force"
  ignore_errors: yes
  when: skip_clean == false

- name: "Clean path of minishift in {{ ansible_env.HOME }}/.bashrc"
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "minishift"
    state: absent

- name: "Clean path of oc in {{ ansible_env.HOME }}/.bashrc"
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "oc"
    state: absent

- name: "Cleanup files and directories"
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
    with_items:
      - "minishift/minishift"
      - "minishift/LICENSE"
      - "minishift/README.adoc"
      - ".minishift"
      - ".kube"
  ignore_errors: yes
