---
- name: "Add minishift addons helm"
  command: "{{ minishift_dest_dir }}/minishift addons install helm"
  when: skip_helm == false

- name: "Apply minishift addons helm"
  command: "{{ minishift_dest_dir }}/minishift addons apply helm"
  when: skip_helm == false

- name: "Set HELM_HOST in {{ ansible_env.HOME }}/.bashrc"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: export HELM_HOST="$(minishift ip):$(oc get svc/tiller -o jsonpath='{.spec.ports[0].nodePort}' -n kube-system --as=system:admin)"
    create: yes
  when: skip_helm == false

- name: "Set MINISHIFT_ADMIN_CONTEXT in {{ ansible_env.HOME }}/.bashrc"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: export MINISHIFT_ADMIN_CONTEXT="default/$(oc config view -o jsonpath='{.contexts[?(@.name=="minishift")].context.cluster}')/system:admin"
    create: yes
  when: skip_helm == false

- name: "Source {{ ansible_env.HOME }}/.bashrc"
  shell: source {{ ansible_env.HOME }}/.bashrc 2>&1
  when: skip_helm == false

- name: "Initialization helm client"
  command: "{{ minishift_dest_dir }}/helm init --client-only"
  when: skip_helm == false
